version: '3.8'

services:
  php:
    image: php:8.1-fpm
    container_name: php-container
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - composer

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  composer:
    image: composer:latest
    container_name: composer-container
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - app-network
    command: install --no-interaction

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - .:/var/www/html
      - C:/Users/julia/Desktop/proyecto/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - php

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
