FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
    unzip \
    git \
    libonig-dev \
    libzip-dev \
    && docker-php-ext-install pdo pdo_mysql zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY php.ini /usr/local/etc/php/conf.d/php.ini

WORKDIR /var/www/html
