<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH0naMli\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH0naMli/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH0naMli.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH0naMli\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH0naMli\App_KernelDevDebugContainer([
    'container.build_hash' => 'H0naMli',
    'container.build_id' => '6414842e',
    'container.build_time' => 1740677703,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH0naMli');
