<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPTTb3VU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPTTb3VU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPTTb3VU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPTTb3VU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPTTb3VU\App_KernelDevDebugContainer([
    'container.build_hash' => 'PTTb3VU',
    'container.build_id' => '1586c7cf',
    'container.build_time' => 1740668767,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPTTb3VU');
